### ISSUE TITLE
Poster Issue

### ISSUE THREAD

**Issue by DarkMask100** [Wizell/JAVMovieScraper#1]
When scraping a file, the poster is not being downloaded correctly and is instead just a blown up version of the fanart.

**Comment by mut3k1** [comment]
I think this issue is from the DMM scrape only, if you remove DMM from the amalgamation list (disable it), it won't happen.  Short term fix!

**Comment by Wizell** [comment]
I'm not totaly sure if i got the problem properly. But i tried a fix.

Can you please tell me if this fixed the issue ?

**Comment by DarkMask100** [comment]
Issue fixed, thanks!
