### ISSUE TITLE
Can't open v0.3.0 version

### ISSUE THREAD

**Issue by Wimi2** [Wizell/JAVMovieScraper#23]
I am running a system with Windows 10 with an updated JAVA. I can see the JAVA file in the task manager, but it crashes shortly after. The software doesn't seem to start at all. I tried out older versions as well: v0.2.29 works fine. Is something wrong with the file or is it my system?

**Comment by Kswing** [comment]
I'm having the same issue as Wimi2. I have the same system environment. (Windows 10 and updated Java). When launching the program, it briefly pops up in task manager then disappears. The older versions work just fine. Please help if you can. Thanks.

**Comment by Wizell** [comment]
Could any of you run the jar file from command line and report any error or message ?
Start->Run then type cmd. Inside the shell type java -jar <PATH TO YOUR JAR FILE> e.g. java -jar d:\JavMovieScraper.jar

Thank you in advance

**Comment by Wimi2** [comment]
Hi, sure!

```
CAPSULE EXCEPTION: Illegal char <"> at index 0: " while processing system property java.library.path: C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Calibre2\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;";C:\WINDOWS\system32\config\systemprofile\adb-fastboot\platform-tools";C:\Program Files (x86)\Skype\Phone\;C:\Users\wimi\AppData\Local\Microsoft\WindowsApps;;. (for stack trace, run with -Dcapsule.log=verbose)
Exception in thread "main" java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at Capsule.toFriendlyPath(Capsule.java:3712)
        at Capsule.printHelp(Capsule.java:1185)
        at Capsule.printUsage(Capsule.java:452)
        at Capsule.printError(Capsule.java:448)
        at Capsule.onError0(Capsule.java:5119)
        at Capsule.onError(Capsule.java:5115)
        at Capsule.main0(Capsule.java:398)
        at Capsule.main(Capsule.java:374)
```

**Comment by Kswing** [comment]
Uninstalling Java and installing Java Build 1.8.0_151-b12 seems to have solved my problem. Thanks

**Comment by Wizell** [comment]
@Kswing It should work well in Java8. The problem should be something else.

@Wimi2 In your case, you have an erroneous java library path. This part is incorrect ;";C:\WINDOWS\system32\config\systemprofile\adb-fastboot\platform-tools"; It should most likely be ;"C:\WINDOWS\system32\config\systemprofile\adb-fastboot\platform-tools"; Can you try this ?

**Comment by Nick8005** [comment]
Hi Wimi2 

Thanks for cross referencing my ticket. 
I also do not seem to be in possession of a adb-fastboot\platform-tools folder, NEITHER in nthe windows, now in the User folder though. 

Also, running "java -jar e.g. java -jar d:\JavMovieScraper.jar" in the console returns "Error, Unable to access jar file, eg."

It seems odd I have this happening on two machines, one running win10 and the other running win 8.1 isnt it? 

Any suggestions? 


Any suggestions?

**Comment by Cutters1982** [comment]
Uninstalling the java version I had and installing Java Build 1.8.0_151-b12 fixed the issue for me as well :)

**Comment by Wizell** [comment]
@Nick8005 Is there no more output than that ?. Can you also try the software adding -xmx1024M to the command line ? (this would be something like java -xmx1024M -jar <put your jar path here>)

**Comment by fidofido300** [comment]
Newly Installed JAVA 8 181
c:\Users\xxxxxx\Desktop\xxxxx\xxxxx\xxxxx>java -Xmx1024M -jar JAVMovieScraper.jar
Error: Could not find or load main class moviescraper.doctord.Main

**Comment by Wizell** [comment]
@fidofido300 This should be fixed by new version. Can you report in DoctorD's repository if there is still an issue ?
