### ISSUE TITLE
American Adult DVD Amalgamation

### ISSUE THREAD

**Issue by slappy2** [Wizell/JAVMovieScraper#29]
Hi,
I don't see the choice Data18WEB in the list of default ordering in American Adult Amalgamation. I would like to combine iafd and data18web together since the actors thumbs are not working using only data18web. Can you add it to the list please ?

**Comment by Wizell** [comment]
@slappy2 This repository is not maintained anymore (see #24). So,  please add this issue to main repository (https://github.com/DoctorD1501/JAVMovieScraper)
